# Generated by Django 2.1 on 2020-05-29 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField(max_length=1000)),
                ('Due_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
