# Generated by Django 2.1 on 2020-06-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
