# Generated by Django 2.1 on 2020-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20200602_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Labels',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Shopping', 'Shopping'), ('Others', 'Others')], default='--', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('New', 'New'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], default='--', max_length=100),
        ),
    ]
